export type CoverTone = "sage" | "forest" | "sand";

export type LibrarySummary = {
  id: string;
  name: string;
  city: string;
  state: string;
  district: string;
  rating: number;
  reviewCount: number;
  monthlyFee: number;
  availableSeats: number;
  totalSeats: number;
  facilities: string[];
  studentTypes: string[];
  coverTone: CoverTone;
  createdAt: string;
};

export type LibraryDetail = LibrarySummary & {
  description: string;
  address: string;
  pincode: string;
  fees: {
    monthly: number;
    quarterly: number;
    annual: number;
  };
};

export type Slot = {
  id: string;
  name: string;
  startTime: string;
  endTime: string;
  totalSeats: number;
  availableSeats: number;
};

export type Review = {
  id: string;
  studentName: string;
  rating: number;
  comment: string;
  isVerified: boolean;
  date: string;
};

export const libraries: LibrarySummary[] = [
  {
    id: "green-arc",
    name: "Green Arc Library",
    city: "Bhopal",
    state: "Madhya Pradesh",
    district: "Bhopal",
    rating: 4.8,
    reviewCount: 128,
    monthlyFee: 900,
    availableSeats: 12,
    totalSeats: 60,
    facilities: ["WiFi", "AC", "CCTV", "Locker"],
    studentTypes: ["Govt Exam", "Entrance Exam"],
    coverTone: "sage",
    createdAt: "2025-11-02",
  },
  {
    id: "pin-drop",
    name: "Pin Drop Reading Hall",
    city: "Indore",
    state: "Madhya Pradesh",
    district: "Indore",
    rating: 4.6,
    reviewCount: 88,
    monthlyFee: 750,
    availableSeats: 6,
    totalSeats: 40,
    facilities: ["Power Backup", "Washroom", "Drinking Water"],
    studentTypes: ["Govt Exam", "Professional"],
    coverTone: "sand",
    createdAt: "2025-10-18",
  },
  {
    id: "focus-point",
    name: "Focus Point Library",
    city: "Kota",
    state: "Rajasthan",
    district: "Kota",
    rating: 4.9,
    reviewCount: 164,
    monthlyFee: 1100,
    availableSeats: 18,
    totalSeats: 80,
    facilities: ["AC", "Parking", "CCTV", "WiFi"],
    studentTypes: ["Entrance Exam", "School"],
    coverTone: "forest",
    createdAt: "2025-12-01",
  },
  {
    id: "sage-collective",
    name: "Sage Study Collective",
    city: "Jaipur",
    state: "Rajasthan",
    district: "Jaipur",
    rating: 4.7,
    reviewCount: 102,
    monthlyFee: 820,
    availableSeats: 9,
    totalSeats: 55,
    facilities: ["WiFi", "Generator", "Locker"],
    studentTypes: ["Govt Exam", "Entrance Exam"],
    coverTone: "sage",
    createdAt: "2025-09-14",
  },
  {
    id: "citylight",
    name: "Citylight Library",
    city: "Delhi",
    state: "Delhi",
    district: "Central Delhi",
    rating: 4.5,
    reviewCount: 74,
    monthlyFee: 980,
    availableSeats: 0,
    totalSeats: 50,
    facilities: ["AC", "CCTV", "Power Backup"],
    studentTypes: ["Professional", "Govt Exam"],
    coverTone: "sand",
    createdAt: "2025-08-22",
  },
  {
    id: "study-haven",
    name: "Study Haven",
    city: "Pune",
    state: "Maharashtra",
    district: "Pune",
    rating: 4.6,
    reviewCount: 90,
    monthlyFee: 880,
    availableSeats: 5,
    totalSeats: 48,
    facilities: ["WiFi", "Parking", "Drinking Water"],
    studentTypes: ["Entrance Exam", "Professional"],
    coverTone: "forest",
    createdAt: "2025-10-05",
  },
  {
    id: "quiet-zone-bhopal",
    name: "Quiet Zone Library",
    city: "Bhopal",
    state: "Madhya Pradesh",
    district: "Bhopal",
    rating: 4.4,
    reviewCount: 61,
    monthlyFee: 650,
    availableSeats: 3,
    totalSeats: 35,
    facilities: ["WiFi", "AC", "Washroom", "Study Material"],
    studentTypes: ["Govt Exam", "School"],
    coverTone: "sage",
    createdAt: "2026-01-10",
  },
  {
    id: "metro-read-indore",
    name: "Metro Read Hall",
    city: "Indore",
    state: "Madhya Pradesh",
    district: "Indore",
    rating: 4.3,
    reviewCount: 55,
    monthlyFee: 720,
    availableSeats: 8,
    totalSeats: 42,
    facilities: ["WiFi", "Locker", "CCTV", "Parking"],
    studentTypes: ["Entrance Exam", "Professional"],
    coverTone: "forest",
    createdAt: "2025-12-15",
  },
  {
    id: "civil-lines-jabalpur",
    name: "Civil Lines Study Hub",
    city: "Jabalpur",
    state: "Madhya Pradesh",
    district: "Jabalpur",
    rating: 4.2,
    reviewCount: 48,
    monthlyFee: 600,
    availableSeats: 14,
    totalSeats: 50,
    facilities: ["WiFi", "Drinking Water", "Generator", "Washroom"],
    studentTypes: ["Govt Exam", "Entrance Exam"],
    coverTone: "sand",
    createdAt: "2025-11-28",
  },
  {
    id: "gwalior-focus",
    name: "Gwalior Focus Library",
    city: "Gwalior",
    state: "Madhya Pradesh",
    district: "Gwalior",
    rating: 4.5,
    reviewCount: 67,
    monthlyFee: 680,
    availableSeats: 0,
    totalSeats: 38,
    facilities: ["AC", "CCTV", "Locker", "Study Material"],
    studentTypes: ["Govt Exam", "School"],
    coverTone: "sage",
    createdAt: "2025-10-30",
  },
  {
    id: "lake-view-bhopal",
    name: "Lake View Reading Room",
    city: "Bhopal",
    state: "Madhya Pradesh",
    district: "Bhopal",
    rating: 4.7,
    reviewCount: 95,
    monthlyFee: 850,
    availableSeats: 11,
    totalSeats: 45,
    facilities: ["WiFi", "AC", "Parking", "CCTV"],
    studentTypes: ["Entrance Exam", "Professional"],
    coverTone: "forest",
    createdAt: "2026-02-01",
  },
  {
    id: "vijay-nagar-indore",
    name: "Vijay Nagar Library",
    city: "Indore",
    state: "Madhya Pradesh",
    district: "Indore",
    rating: 4.1,
    reviewCount: 42,
    monthlyFee: 550,
    availableSeats: 2,
    totalSeats: 30,
    facilities: ["WiFi", "Washroom", "Drinking Water"],
    studentTypes: ["School", "Govt Exam"],
    coverTone: "sand",
    createdAt: "2025-09-05",
  },
  {
    id: "fort-campus-gwalior",
    name: "Fort Campus Library",
    city: "Gwalior",
    state: "Madhya Pradesh",
    district: "Gwalior",
    rating: 4.6,
    reviewCount: 73,
    monthlyFee: 790,
    availableSeats: 7,
    totalSeats: 40,
    facilities: ["WiFi", "AC", "Locker", "Generator"],
    studentTypes: ["Entrance Exam", "Govt Exam"],
    coverTone: "forest",
    createdAt: "2025-12-20",
  },
  {
    id: "wright-town-jabalpur",
    name: "Wright Town Study Centre",
    city: "Jabalpur",
    state: "Madhya Pradesh",
    district: "Jabalpur",
    rating: 3.9,
    reviewCount: 36,
    monthlyFee: 500,
    availableSeats: 16,
    totalSeats: 52,
    facilities: ["WiFi", "CCTV", "Washroom", "Parking"],
    studentTypes: ["Govt Exam", "Professional"],
    coverTone: "sage",
    createdAt: "2025-08-10",
  },
  {
    id: "kolar-road-bhopal",
    name: "Kolar Road Library",
    city: "Bhopal",
    state: "Madhya Pradesh",
    district: "Bhopal",
    rating: 4.8,
    reviewCount: 112,
    monthlyFee: 950,
    availableSeats: 4,
    totalSeats: 44,
    facilities: ["WiFi", "AC", "Locker", "Study Material", "CCTV"],
    studentTypes: ["Entrance Exam", "Govt Exam"],
    coverTone: "sand",
    createdAt: "2026-01-25",
  },
  {
    id: "palasia-indore",
    name: "Palasia Reading Library",
    city: "Indore",
    state: "Madhya Pradesh",
    district: "Indore",
    rating: 4.9,
    reviewCount: 140,
    monthlyFee: 1200,
    availableSeats: 20,
    totalSeats: 70,
    facilities: ["WiFi", "AC", "Parking", "Generator", "CCTV"],
    studentTypes: ["Entrance Exam", "Professional"],
    coverTone: "forest",
    createdAt: "2026-02-10",
  },
  {
    id: "hoshangabad-road-bhopal",
    name: "Hoshangabad Road Study Hall",
    city: "Bhopal",
    state: "Madhya Pradesh",
    district: "Bhopal",
    rating: 4.0,
    reviewCount: 51,
    monthlyFee: 700,
    availableSeats: 9,
    totalSeats: 36,
    facilities: ["WiFi", "Drinking Water", "Washroom", "Locker"],
    studentTypes: ["School", "Govt Exam"],
    coverTone: "sage",
    createdAt: "2025-11-08",
  },
  {
    id: "maharaja-jabalpur",
    name: "Maharaja Study Library",
    city: "Jabalpur",
    state: "Madhya Pradesh",
    district: "Jabalpur",
    rating: 4.5,
    reviewCount: 58,
    monthlyFee: 640,
    availableSeats: 1,
    totalSeats: 28,
    facilities: ["AC", "CCTV", "Study Material", "WiFi"],
    studentTypes: ["Govt Exam", "Entrance Exam"],
    coverTone: "forest",
    createdAt: "2025-10-12",
  },
  {
    id: "city-centre-gwalior",
    name: "City Centre Library",
    city: "Gwalior",
    state: "Madhya Pradesh",
    district: "Gwalior",
    rating: 3.8,
    reviewCount: 29,
    monthlyFee: 520,
    availableSeats: 13,
    totalSeats: 46,
    facilities: ["WiFi", "Parking", "Washroom", "Generator"],
    studentTypes: ["Professional", "School"],
    coverTone: "sand",
    createdAt: "2025-07-19",
  },
  {
    id: "premium-kota",
    name: "Premium Study Lounge",
    city: "Kota",
    state: "Rajasthan",
    district: "Kota",
    rating: 4.7,
    reviewCount: 118,
    monthlyFee: 1500,
    availableSeats: 15,
    totalSeats: 90,
    facilities: ["WiFi", "AC", "Locker", "CCTV", "Study Material"],
    studentTypes: ["Entrance Exam", "School"],
    coverTone: "sage",
    createdAt: "2026-01-05",
  },
  {
    id: "pink-city-jaipur",
    name: "Pink City Library",
    city: "Jaipur",
    state: "Rajasthan",
    district: "Jaipur",
    rating: 4.4,
    reviewCount: 64,
    monthlyFee: 880,
    availableSeats: 6,
    totalSeats: 48,
    facilities: ["WiFi", "AC", "Parking", "Washroom"],
    studentTypes: ["Govt Exam", "Entrance Exam"],
    coverTone: "forest",
    createdAt: "2025-12-08",
  },
  {
    id: "connaught-delhi",
    name: "Connaught Study Space",
    city: "Delhi",
    state: "Delhi",
    district: "New Delhi",
    rating: 4.6,
    reviewCount: 86,
    monthlyFee: 1800,
    availableSeats: 3,
    totalSeats: 55,
    facilities: ["WiFi", "AC", "Locker", "CCTV", "Generator"],
    studentTypes: ["Professional", "Govt Exam"],
    coverTone: "sand",
    createdAt: "2025-11-20",
  },
  {
    id: "fc-road-pune",
    name: "FC Road Study Library",
    city: "Pune",
    state: "Maharashtra",
    district: "Pune",
    rating: 4.3,
    reviewCount: 52,
    monthlyFee: 920,
    availableSeats: 10,
    totalSeats: 50,
    facilities: ["WiFi", "Parking", "Drinking Water", "Study Material"],
    studentTypes: ["Entrance Exam", "Professional"],
    coverTone: "sage",
    createdAt: "2025-10-25",
  },
];

export const libraryDetails: Record<string, LibraryDetail> = {
  "green-arc": {
    ...libraries[0],
    description:
      "A quiet, well-ventilated space with ergonomic seating and dedicated UPSC study zones.",
    address: "12, Arera Colony Main Road, Near City Park",
    pincode: "462016",
    fees: {
      monthly: 900,
      quarterly: 2500,
      annual: 9000,
    },
  },
  "pin-drop": {
    ...libraries[1],
    description:
      "Compact library focused on serious aspirants with power backup and strict silence hours.",
    address: "27, Saket Nagar, Behind Metro Mall",
    pincode: "452018",
    fees: {
      monthly: 750,
      quarterly: 2100,
      annual: 8200,
    },
  },
  "focus-point": {
    ...libraries[2],
    description:
      "Spacious study hall designed for entrance exam prep with high-speed WiFi and AC zones.",
    address: "45, Landmark Avenue, Coaching District",
    pincode: "324005",
    fees: {
      monthly: 1100,
      quarterly: 3200,
      annual: 11800,
    },
  },
  "sage-collective": {
    ...libraries[3],
    description:
      "Community-focused library with flexible shifts and curated exam resources for UPSC prep.",
    address: "88, C-Scheme, Near Central Library",
    pincode: "302001",
    fees: {
      monthly: 820,
      quarterly: 2350,
      annual: 8800,
    },
  },
  citylight: {
    ...libraries[4],
    description:
      "Central Delhi study hub with private cubicles, digital ID access, and CCTV security.",
    address: "22, Connaught Place, Block B",
    pincode: "110001",
    fees: {
      monthly: 980,
      quarterly: 2800,
      annual: 9800,
    },
  },
  "study-haven": {
    ...libraries[5],
    description:
      "Calm, boutique library for working professionals with early-morning slots and lockers.",
    address: "17, FC Road, Near University Gate",
    pincode: "411004",
    fees: {
      monthly: 880,
      quarterly: 2450,
      annual: 9200,
    },
  },
};

export const librarySlots: Record<string, Slot[]> = {
  "green-arc": [
    {
      id: "morning",
      name: "Morning",
      startTime: "06:00 AM",
      endTime: "12:00 PM",
      totalSeats: 20,
      availableSeats: 6,
    },
    {
      id: "afternoon",
      name: "Afternoon",
      startTime: "12:00 PM",
      endTime: "06:00 PM",
      totalSeats: 20,
      availableSeats: 4,
    },
    {
      id: "night",
      name: "Night",
      startTime: "06:00 PM",
      endTime: "12:00 AM",
      totalSeats: 20,
      availableSeats: 2,
    },
  ],
  "pin-drop": [
    {
      id: "morning",
      name: "Morning",
      startTime: "07:00 AM",
      endTime: "01:00 PM",
      totalSeats: 15,
      availableSeats: 3,
    },
    {
      id: "afternoon",
      name: "Afternoon",
      startTime: "01:00 PM",
      endTime: "07:00 PM",
      totalSeats: 15,
      availableSeats: 2,
    },
    {
      id: "night",
      name: "Night",
      startTime: "07:00 PM",
      endTime: "12:30 AM",
      totalSeats: 10,
      availableSeats: 1,
    },
  ],
  "focus-point": [
    {
      id: "morning",
      name: "Morning",
      startTime: "05:30 AM",
      endTime: "12:00 PM",
      totalSeats: 30,
      availableSeats: 10,
    },
    {
      id: "afternoon",
      name: "Afternoon",
      startTime: "12:00 PM",
      endTime: "06:30 PM",
      totalSeats: 30,
      availableSeats: 6,
    },
    {
      id: "night",
      name: "Night",
      startTime: "06:30 PM",
      endTime: "12:30 AM",
      totalSeats: 20,
      availableSeats: 2,
    },
  ],
  "sage-collective": [
    {
      id: "morning",
      name: "Morning",
      startTime: "06:30 AM",
      endTime: "12:30 PM",
      totalSeats: 18,
      availableSeats: 4,
    },
    {
      id: "afternoon",
      name: "Afternoon",
      startTime: "12:30 PM",
      endTime: "06:30 PM",
      totalSeats: 18,
      availableSeats: 3,
    },
    {
      id: "night",
      name: "Night",
      startTime: "06:30 PM",
      endTime: "12:00 AM",
      totalSeats: 19,
      availableSeats: 2,
    },
  ],
  citylight: [
    {
      id: "morning",
      name: "Morning",
      startTime: "07:00 AM",
      endTime: "01:00 PM",
      totalSeats: 18,
      availableSeats: 0,
    },
    {
      id: "afternoon",
      name: "Afternoon",
      startTime: "01:00 PM",
      endTime: "07:00 PM",
      totalSeats: 18,
      availableSeats: 0,
    },
    {
      id: "night",
      name: "Night",
      startTime: "07:00 PM",
      endTime: "12:00 AM",
      totalSeats: 14,
      availableSeats: 0,
    },
  ],
  "study-haven": [
    {
      id: "morning",
      name: "Morning",
      startTime: "06:00 AM",
      endTime: "11:30 AM",
      totalSeats: 16,
      availableSeats: 2,
    },
    {
      id: "afternoon",
      name: "Afternoon",
      startTime: "11:30 AM",
      endTime: "05:30 PM",
      totalSeats: 16,
      availableSeats: 1,
    },
    {
      id: "night",
      name: "Night",
      startTime: "05:30 PM",
      endTime: "11:00 PM",
      totalSeats: 16,
      availableSeats: 2,
    },
  ],
};

export const libraryReviews: Record<string, Review[]> = {
  "green-arc": [
    {
      id: "review-1",
      studentName: "Ritika S.",
      rating: 5,
      comment: "Super calm environment and helpful staff. Seats are spacious.",
      isVerified: true,
      date: "Mar 18, 2026",
    },
    {
      id: "review-2",
      studentName: "Anuj K.",
      rating: 4,
      comment: "Great facilities. Slightly busy in the evening slot.",
      isVerified: true,
      date: "Feb 02, 2026",
    },
  ],
  "pin-drop": [
    {
      id: "review-3",
      studentName: "Sonal M.",
      rating: 4,
      comment: "Quiet and disciplined. Power backup is reliable.",
      isVerified: true,
      date: "Apr 11, 2026",
    },
    {
      id: "review-4",
      studentName: "Vikas R.",
      rating: 4,
      comment: "Good for working professionals, slots are flexible.",
      isVerified: false,
      date: "Jan 20, 2026",
    },
  ],
  "focus-point": [
    {
      id: "review-5",
      studentName: "Aditi P.",
      rating: 5,
      comment: "Best seating and ambience in Kota. Worth the fee.",
      isVerified: true,
      date: "May 05, 2026",
    },
    {
      id: "review-6",
      studentName: "Rohan D.",
      rating: 5,
      comment: "Perfect for JEE prep. Love the late-night slot.",
      isVerified: true,
      date: "Mar 29, 2026",
    },
  ],
  "sage-collective": [
    {
      id: "review-7",
      studentName: "Meera J.",
      rating: 5,
      comment: "Organized and secure. Lockers are helpful.",
      isVerified: true,
      date: "Feb 16, 2026",
    },
    {
      id: "review-8",
      studentName: "Kabir T.",
      rating: 4,
      comment: "Friendly staff and good facilities.",
      isVerified: true,
      date: "Jan 10, 2026",
    },
  ],
  citylight: [
    {
      id: "review-9",
      studentName: "Nisha G.",
      rating: 4,
      comment: "Great location, but seats fill quickly.",
      isVerified: true,
      date: "Apr 01, 2026",
    },
  ],
  "study-haven": [
    {
      id: "review-10",
      studentName: "Pavan L.",
      rating: 4,
      comment: "Cozy and clean. Early morning slot is quiet.",
      isVerified: false,
      date: "Feb 22, 2026",
    },
  ],
};
